Parameters:
  MainRegion:
    Description: Region which is designated as main Region and use condition to only deploy resources if it is in main region like IAM resources
    Default: us-east-1
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ap-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - sa-east-1
    AllowedPattern: ^.{0,14}$
    ConstraintDescription: Select one AWS Region only.
    Type: String
  AutomationAssumeRoleName:
    Type: String
    Description: EC2_INSTANCE_NO_PUBLIC_IP auto-remediation IAM role name
    Default: EC2_INSTANCE_NO_PUBLIC_IP-remediation-iam

Conditions:
  IsMainRegion: !Equals [ !Ref 'AWS::Region', !Ref MainRegion ]

Resources:
  AutomationAssumeRole:
    Condition: IsMainRegion
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
      Policies:
        - PolicyName: !Ref AutomationAssumeRoleName
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'ec2:*'
                Resource: '*'