Parameters:
  MainRegion:
    Description: Region which is designated as main Region in your Compliance Account.
    Default: us-east-1
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - ap-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - sa-east-1
    AllowedPattern: ^.{0,14}$
    ConstraintDescription: Select one AWS Region only.
    Type: String
  CreateOpsItemRoleName:
    Type: String
    Description: cloudwatch IAM role name
    Default: S3-BUCKET-SERVER-SIDE-ENCRYPTION-ENABLED-createOpsItem-iam
  Stage:
    Type: String
    Description: Deploy to Gamma or Prod Endpoint for Ops Center
    Default: Prod
    AllowedValues:
      - Gamma
      - Prod
  CloudWatchEventIAMRole:
    Type: String
    Description: The IAM role that grants CloudWatchEvent access to create OpsItems
    Default: service-role/AWS_Events_Invoke_Create_Ops_Item_1865820173

Conditions:
  IsMainRegion: !Equals [ !Ref 'AWS::Region', !Ref MainRegion ]

Mappings:
  Settings:
    SnSOpsItem:
      Prod: 946491653051
      Gamma: 111111111111

Resources:
  CreateOpsItemRole:
    Condition: IsMainRegion
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
      Path: /
      Policies:
        - PolicyName: !Ref CreateOpsItemRoleName
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'ssm:CreateOpsItem'
                Resource: '*'
  CheckCloudTrailCloudWatchLogsConfigRuleCloudWatchEvent:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: "CloudWatch Rule which creates Ops Items for CloudTrail Compliance Events"
      EventPattern:
        source:
          - aws.config
        detail-type:
          - 'Config Rules Compliance Change'
        detail:
          configRuleName:
            - S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED_v2
          newEvaluationResult:
            complianceType:
              - NON_COMPLIANT
      State: "ENABLED"
      Targets:
        - Arn: !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:opsitem
          Id: SSM-OpsItem
          RoleArn: !GetAtt CreateOpsItemRole.Arn
          InputTransformer:
            InputTemplate:
              Fn::Sub:
                - '{ "title": "CloudTrail CloudWatch Logs Compliance Failure",
                       "description": "CloudWatch Event Rule was triggered for Config Compliance Rule Failure.",
                       "source": "Config Compliance",
                       "priority": "2",
                       "severity": "1",
                       "notifications": [{ "arn": "arn:${AWS::Partition}:sns:${AWS::Region}:${accountId}:OpsCenterEventNotificationTopic"}],
                       "resources": <resources>,
                       "operationalData": {
                         "/aws/dedup": {"type": "SearchableString","value": "{\"dedupString\":\"SSMOpsItems-S3-Encrypted-enabled-failed\"}"},
                         "/aws/automations": { "value": "[ { \"automationType\": \"AWS:SSM:Automation\", \"automationId\": \"AWS-EnableS3BucketEncryption\" } ]" },
                         "/aws/resources": {"value": "[{\"arn\":\"arn:aws:s3:::$resourceID\"}]","type": "SearchableString"},
                         "configRuleName": {"type": "SearchableString","value": <configRuleName>},
                         "resourceType": {"type": "SearchableString","value": <resourceType>},
                         "resourceId": {"type": "SearchableString","value": <resourceId>}
                       }
                     }'
                - accountId: !FindInMap [Settings, SnSOpsItem, !Ref Stage]
            InputPathsMap:
              configRuleName: "$.configRuleName"
              resources: "$.resources"
              resourceType: "$.detail.resourceType"
              resourceId: "$.detail.resourceId"